local opt = vim.opt

opt.number = true
opt.relativenumber = true
opt.cursorline = true
opt.signcolumn = "yes"
opt.scrolloff = 6
opt.sidescrolloff = 6
opt.colorcolumn = "100"
opt.termguicolors = true
opt.showmode = false
opt.laststatus = 3
opt.splitbelow = true
opt.splitright = true
opt.confirm = true
opt.undofile = true
opt.ignorecase = true
opt.smartcase = true
opt.incsearch = true
opt.updatetime = 250
opt.timeoutlen = 400
opt.completeopt = { "menu", "menuone", "noselect" }
opt.expandtab = true
opt.tabstop = 4
opt.shiftwidth = 4
opt.softtabstop = 4
opt.smartindent = true
opt.breakindent = true
opt.linebreak = true
opt.spelllang = "en"
opt.wrap = false
